site_name: DeepLearning
site_url: https://dplrn.ai
site_description: DeepLearning

repo_url: https://github.com/xuehangcang/DeepLearning
repo_name: xuehangcang/DeepLearning

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
  logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  #  主题灯光
  palette:
    primary: white
    accent: white
  font:
    text: Roboto
  homepage: https://dplrn.ai

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
 - mkdocs-jupyter:
 - search:
     lang: en

edit_uri: "https://github.com/xuehangcang/DeepLearning"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xuehangcang
    - icon: fontawesome/brands/github
      link: https://github.com/xuehangcang
    - icon: fontawesome/solid/paper-plane
      link: mailto:xuehangcang@outlook.com
copyright: Copyright &copy; 2023 Xuehang Cang

nav:
  - DeepLearning: 'index.md'
#  - Python:
#    - 面向对象: 'Python/面向对象.md'
#    - 进阶语法: 'Python/进阶语法.md'
  - PyTorch:
      - Pytorch: 'PyTorch/Pytorch.md'
      - Pytorch 快速入门:
        - 1.快速入门: 'PyTorch/Pytorch 快速入门/1.快速入门.ipynb'
        - 2.张量: 'PyTorch/Pytorch 快速入门/2.张量.ipynb'
        - 3.数据集和数据加载器: 'PyTorch/Pytorch 快速入门/3.数据集和数据加载器.ipynb'
        - 4.变换: 'PyTorch/Pytorch 快速入门/4.变换.ipynb'
        - 5.构建神经网络: 'PyTorch/Pytorch 快速入门/5.构建神经网络.ipynb'
        - 6.自动微分: 'PyTorch/Pytorch 快速入门/6.自动微分.ipynb'
        - 7.优化模型参数: 'PyTorch/Pytorch 快速入门/7.优化模型参数.ipynb'
        - 8.保存和加载模型: 'PyTorch/Pytorch 快速入门/8.保存和加载模型.ipynb'
      - Pytorch 论文复现:
          - 卷积神经网络:
            - 1.AlexNet: 'PyTorch/Pytorch 论文复现/卷积神经网络/1.AlexNet.ipynb'
          - 循环神经网络:
            - 1.LSTM: 'PyTorch/Pytorch 论文复现/循环神经网络/1.LSTM.ipynb'